### ISSUE TITLE
Build fails: file not found for module `to`

### ISSUE THREAD

**Issue by skligys** [dobkeratops/android_rust_gl#1]
I tried to build the most recent version, and it fails:

$ make
echo "Building Rust source as a library..."
Building Rust source as a library...
LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64 rustc --target=arm-linux-androideabi ../main.rs -C linker=/home/skligys/Work/Android/android-ndk-standalone/bin/arm-linux-androideabi-gcc --crate-type=staticlib -o jni/librust_android.a
../r3d/mod.rs:13:9: 13:11 error: file not found for module `to`
../r3d/mod.rs:13 pub mod to;
                         ^~
make: **\* [jni/librust_android.a] Error 101

It looks that you forgot to check in files to.rs and half.rs.  The version as of 7/5/2014 builds OK.

**Comment by dobkeratops** [comment]
thanks.. i'll add those. I hand't been trying this out on android either lately.
